# Informações do Projeto
site_name: wGalleti
site_description: 'Uteis de wGalleti'
site_author: 'William Galleti'
site_url: 'https://medocs.disqus.com'

# Documentos e Temas
docs_dir: 'docs'

# Copyright
copyright: '© 2017 wGalleti'

theme:
  name: 'material'
  language: 'pt'
  palette:
    primary: 'red'
    accent: 'orange'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo:
    icon: 'cloud'
  feature:
    tabs: true

# Opções
extra:
  disqus: 'mkdocs-material'
  search:
    tokenizer: '[\s\-\.]+'
  social:
    - type: 'github'
      link: 'https://github.com/wGalleti'
    - type: 'twitter'
      link: 'https://twitter.com/wGalleti'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/william-galleti-6b97a833/'

# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false,linenums=true)
  - toc(permalink=true)
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

# Paginas
pages:
  - 'Home': 'index.md'
  - 'Servidores':
    - 'Nginx':
        - 'Python': 'servidores/nginx/python.md'
        - 'Scheffer': 'servidores/nginx/gruposcheffer.md'
        - 'PHP': 'servidores/nginx/php.md'
    - 'Apache':
        - 'Python': 'servidores/apache/python.md'
  - 'Oracle':
    - 'PL/SQL':
      - 'uteis': 'oracle/plsql/uteis.md'
  - 'Desenvolvimento':
    - 'Python/Django':
      - 'Projeto Heroku': 'desenvolvimento/pythondjango/heroku.md'
      - 'Rest Framework': 'desenvolvimento/pythondjango/rest_framework.md'
      - 'Queries': 'desenvolvimento/pythondjango/queries.md'
      - 'Ldap Windows': 'desenvolvimento/pythondjango/ldap.md'
      - 'Celery': 'desenvolvimento/pythondjango/celery.md'
    - 'JavaScript/Vue':
      - 'Telerik':
        - 'StartProject': 'desenvolvimento/javascriptvue/telerik/startproject.md'
        - 'Samples': 'desenvolvimento/javascriptvue/telerik/samples.md'
    